config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :restaurants do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [] do
    collection do
      get 'latest'
    end
  end
  root 'restaurants#index'

end

app/models/concerns/param_aware.rb
module ParamAware
	def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include ParamAware
  belongs_to :creator, class_name: 'User'
  has_many :reviews
  validates :creator, presence: true
  validates :name, presence: true
  validates :cuisine, presence: true

  delegate :username, to: :creator, prefix:true

  def editable_by? user
    creator == user
  end

  def reviewable_by? user
    creator != user
  end

  def average_rating
    reviews.average(:rating)  || 0
  end

  def self.by_average_rating
     join_clause = 'left outer join reviews on reviews.restaurant_id = restaurants.id'
     joins(join_clause).group(:id).order('avg(reviews.rating) desc nulls last')
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  include ParamAware
  belongs_to :restaurant
  belongs_to :reviewer, class_name: 'User'
  validates :body, presence: true
  validates :rating, presence: true
  validates :reviewer, presence: true
  validates :rating, numericality: {only_integer: true,
    greater_than: 0,
    less_than: 6 }

  delegate :username, to: :reviewer, allow_nil: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :restaurants, foreign_key: :creator_id
  has_many :reviews, foreign_key: :reviewer_id
  validates :email, presence: true, uniqueness: true

  before_save :downcase_email

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  before_action :ensure_current_user, only: [:new, :create, :update, :destroy]

  def current_user
    user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def ensure_current_user
    redirect_to new_session_path unless current_user
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :ensure_owner, only: [:edit, :update, :destroy]

  def index
    if  params[:order] == "rating"
      @restaurants = Restaurant.by_average_rating
    elsif params[:order] == "cuisine"
      @restaurants = Restaurant.order([:cuisine, :name])
    else
      @restaurants = Restaurant.order(:name)
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      flash.notice = 'Restaurant saved'
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash.notice = 'Restaurant saved'
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def ensure_owner
    @restaurant = Restaurant.find(params[:id])
    unless @restaurant.editable_by? current_user
      flash[:error] = "You may not update #{@restaurant.name}"
      redirect_to restaurant_path(@restaurant)
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine, :address, :city, :state, :zip).merge(creator:current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    if @restaurant.reviewable_by? current_user
      create_review @restaurant
    else
      flash.alert = 'You may not review your own restaurant'
      render 'restaurants/show'
    end
  end

  def latest
    @latest = Review.includes(:restaurant).order(created_at: :desc).limit(10)
  end

  private

  def create_review restaurant
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      flash.notice = 'Thanks for your review'
      redirect_to restaurant_path(@restaurant)
    else
      flash.alert = 'Sorry your review failed to save'
      render 'restaurants/show'
    end
  end

  def review_params
    params.require(:review).permit(:rating, :body).merge(reviewer: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_current_user

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash.notice = 'Welcome back'
      redirect_to root_path
    else
      flash[:error] = 'Login failed'
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_current_user
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for registering"
      redirect_to '/users/new'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def std_format_date date
    return "" unless date
    date.strftime("%-d-%b-%Y at %l:%M %p")
  end

  def round_to_1_place number
    sprintf('%.1f', number)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash.any?  %>
    <div id="flash-container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "flash-#{name}" %>
      <% end %>
    </div>
  <% end %>
  <div class="welcome-bar">
    <% if current_user %>
       Welcome <%= current_user.username %>
       <%= link_to 'Log out', session_path, method: :delete %>
    <% else %>
       <%= link_to 'Log in', new_session_path %>
    <% end %>
    <%= link_to 'Home', root_path %>
  </div>

<%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
       <li class="error"><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @restaurant do |f| %>
  <% [:name, :cuisine, :address, :city, :state, :zip].each do |field|  %>
    <div>
      <%= f.label field %>
      <%= f.text_field field %>
    </div>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<li class="restaurant-list-item"><%= link_to restaurant.name, restaurant_path(restaurant) %>
(<%= restaurant.cuisine %>)
Rating: <%= round_to_1_place(restaurant.average_rating) %>
</li>

app/views/restaurants/edit.html.erb
<%= render 'form'  %>

app/views/restaurants/index.html.erb
<h1 data-purpose="header">Restaurants</h1>
Sort: <%= link_to 'Name', restaurants_path %> |
<%= link_to 'Cuisine', restaurants_path({order: :cuisine}) %> |
<%= link_to 'Rating', restaurants_path({order: :rating}) %>

<ul id="restaurant-index">
  <%= render @restaurants %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'form'  %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<dl class="restaurant-data">
  <dt>Creator:</dt>
  <dd><%= @restaurant.creator_username %></dd>
  <dt>Cuisine:</dt>
  <dd><%= @restaurant.cuisine %></dd>
  <dt>Address:</dt>
  <dd><%= @restaurant.address %> <%= @restaurant.city %> <%= @restaurant.state %> <%= @restaurant.zip %></dd>
</dl>

<% if @restaurant.editable_by? current_user %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?'} %>
<% end %>

<h2>Reviews</h2>
<%= render @restaurant.reviews %>

<% if @restaurant.reviewable_by? current_user %>

<h2>Add your review</h2>
  <%= form_for [@restaurant, @review] do |f| %>
     <div>
       <%= f.label :rating %>
       <%= f.select :rating, ['Please choose one', 1,2,3,4,5]%>
     </div>
     <div>
       <%= f.label :body %>
       <%= f.text_area :body, rows:10, cols:80 %>
     </div>

     <div>
       <%= f.submit %>
     </div>
  <% end %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">
 <div class="author-strap">Review from <%=  review.username %> at <%= std_format_date review.created_at %></div>
 <div>
   <%= review.body %>
 </div>
</div>

app/views/reviews/latest.html.erb
<h1>Latest Reviews</h1>

<% @latest.each do |review| %>
  <div class="review">

   <div class="author-strap">Review from <%=  review.username %>
     at <%= std_format_date review.created_at %>
   </div>

   <div>
     <%= review.body %>
   </div>

   <div class="restaurant-summary" data-restaurant-id="<%= review.restaurant.id %>" >
     Restaurant: <%= review.restaurant.name %> (<%= review.restaurant.cuisine %>)
   </div>

  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<fieldset>
  <legend>Please Register</legend>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
</fieldset>
<% end %>

<% if @user.errors.any? %>
  <div class="error_report">
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  </div>
<% end %>